### PR TITLE
Fixes rootMargin logic in `Visible`

### LINKED ISSUE #221: Possible to change unit of rootMargin in Visible component?
I'm using the [Visible](https://github.com/reuters-graphics/graphics-components/blob/3cd997f3f67eb275c6b265bb4dc0c7c5138f8324/src/components/Visible/Visible.svelte) component for the first time. It's great! I'm curious if it's possible to create a prop that would specify whether the rootMargin is using `px` or `%`. Right now it seems like it's hard-coded as `px`. Percent would be helpful to me since screen heights often change so setting a percent is more reliable. (300px on a phone very different from on desktop, but 50% works across both)

### PR DESCRIPTION
**Pull request by MinamiFunakoshiTR**
### Background
I revisited this component after https://github.com/reuters-graphics/graphics-components/issues/221 was filed. The short answer on https://github.com/reuters-graphics/graphics-components/issues/221 is that we should stick to only allowing `px`. This is because `getBoundingClientRect` only works with px, and rootMargin only works with px or % and no relative units like vh.

When revisiting this component, I discovered that the rootMargin props weren't working. For example, even when I set `top` to `200px`, the `visible` variable switched values when the top of the container came into view, not 200px above the top of the container. 

Previously, the component used two methods to check whether the container is visible: IntersectionObserver and calculations based on the top, bottom, right and left values from `container.getBoundingClientRect()`. 

The main issues were:
- IntersectionObserver was firing in `onMount` only
- IntersectionObserver wasn't honouring the top, bottom, right, left values 
- The function `handler` wasn't firing at all, probably partly because of Svelte 5 changes in how it handles events 

I tested both methods and came to the conclusion that we only need `container.getBoundingClientRect()` to control the value for `visible`, so in this PR, I got rid of IntersectionObserver in onMount and rewrote `handler` so that it would fire properly.

### What's in this pull request
- Gets rid of IntersectionObserver in onMount
- Uses Svelte's `<svelte:window onscroll>` to trigger scroll events and removes `window.addEventListener('scroll', handler)
- Renames and tweaks `handler` to `scrollHandler`
- Adds a `not-visible` and `visible` class to the container div 
- Updates docs
- Adds a demo page.

### CODE REVIEW

File: src/components/Visible/Visible.svelte [hunk 1]
```diff
@@ -53,17 +65,17 @@
...
     }
     function handler() {
       if (container) {
         const bcr = container.getBoundingClientRect();
         visible =
-          bcr.bottom + bottom > 0 &&
-          bcr.right + right > 0 &&
-          bcr.top - top < window.innerHeight &&
-          bcr.left - left < window.innerWidth;
+          bcr.bottom + bottom.value > 0 &&
```
Comment (hobbes7878) [inline src/components/Visible/Visible.svelte:75]: This doesn't work if bottom value is in anything other than `px`, right? Can't add `vw` to `px` value from clientRect..

**Review by hobbes7878 — CHANGES_REQUESTED** [review]
I don't think this works in the handler where different numeric values are being compared to px values. Also not a huge fan of having to specify the number and the unit separately. Except for the handler logic, you could just pass in a string for the rootMargin then we can write it just like a CSS value: `top="10px` `bottom="10vh"`, etc. But gotta figure out an alternative to the handler before we can think about merging this.

File: src/components/Visible/Visible.svelte (hunk 1 above)
Comment (MinamiFunakoshiTR) [reply src/components/Visible/Visible.svelte]: yeah, only `px` works here

**Review by hobbes7878 — CHANGES_REQUESTED** [review]
Hey, hey. Don't think we can't _lose_ IntersectionObserver. The whole reason it's there is so we have a _performant_ way to detect when an element is in view. Using a scroll handler is actually a bit of a step backwards.

From the IntersectionObserver API docs:

> Implementing intersection detection in the past involved event handlers and loops calling methods like [Element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to build up the needed information for every element affected. Since all this code runs on the main thread, even one of these can cause performance problems. When a site is loaded with these tests, things can get downright ugly.
> https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by MinamiFunakoshiTR** [comment]
Made further fixes; the first comment in this PR is updated with notes on what changed and why.
Ready for another review

**Comment by hobbes7878** [comment]
> Do you remember why you added getBoundingClient in the first place?

It was a backup for browsers that didn't yet have the IntersectionObserver API, but I think we can probably forgo that in 2025.

**Comment by MinamiFunakoshiTR** [comment]
> > Do you remember why you added getBoundingClient in the first place?
> 
> It was a backup for browsers that didn't yet have the IntersectionObserver API, but I think we can probably forgo that in 2025.

Ah, got it. The PR is ready for a (hopefully) final review.

File: src/components/Visible/Visible.svelte [hunk 2]
```diff
@@ -56,25 +56,15 @@
         if (container) observer.observe(container);
```
[the remark this answers is not in the document]
Comment (MinamiFunakoshiTR) [reply src/components/Visible/Visible.svelte:56]: For type reasons, we need to add an `if (container)` check. We can make it `if (container && observer)`, though -- would you prefer that?
